name: Generate Bomberman

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'bomberman'

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist
          publish_branch: output-games
          force_orphan: true
